[package]
name = "endarke/sequence"
description = "A simple task sorting module, used to shorten the workload."
license = "MPL-2.0"
authors = ["EnDarke"]
version = "1.3.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src", "src/**", "wally.toml", "default.project.json"]
exclude = ["**"]

[dependencies]
